"""UI-neutral application workflow for Proof Assistant."""

from .contracts import (
    AdaptiveHistoryResetResult,
    BenchmarkKind,
    BenchmarkResult,
    CalibrationResetResult,
    CancellationReport,
    ChangeImpactPlan,
    ClarificationPresentation,
    ConcurrencySettingsView,
    EffectiveConcurrencyView,
    FailureArtifact,
    FailureComponent,
    FailureComponentEdge,
    FailureDependencyReport,
    FailureGraphEdge,
    FailureGraphNode,
    FailureIncident,
    FailureKind,
    FailureOutlineNode,
    FailurePath,
    FailureScope,
    FileChange,
    FindingSummary,
    LatexSourceCandidate,
    LegacySettingsView,
    MachineSettingsSnapshot,
    MachineSettingsUpdateRequest,
    NewProjectRequest,
    ProgressEvent,
    ProjectAvailability,
    ProjectCatalogEntry,
    ProjectDeletionAvailability,
    ProjectDeletionInspection,
    ProjectDeletionResult,
    ProjectDestinationInspection,
    ProjectSummary,
    ReportDocument,
    ResourceTelemetryView,
    SettingResolution,
    SettingsChangePreview,
    SettingsScopeKind,
    SettingsWarning,
    SourceInspection,
    SourceLocation,
    VerificationJob,
    VerificationJobObservation,
    VerificationJobState,
    VerificationSettings,
    WorkflowSnapshot,
    WorkflowState,
)

__all__ = [
    "BenchmarkKind",
    "BenchmarkResult",
    "AdaptiveHistoryResetResult",
    "CalibrationResetResult",
    "CancellationReport",
    "ChangeImpactPlan",
    "ClarificationPresentation",
    "ConcurrencySettingsView",
    "EffectiveConcurrencyView",
    "FileChange",
    "FailureArtifact",
    "FailureComponent",
    "FailureComponentEdge",
    "FailureDependencyReport",
    "FailureGraphEdge",
    "FailureGraphNode",
    "FailureIncident",
    "FailureKind",
    "FailureOutlineNode",
    "FailurePath",
    "FailureScope",
    "FindingSummary",
    "LatexSourceCandidate",
    "LegacySettingsView",
    "MachineSettingsSnapshot",
    "MachineSettingsUpdateRequest",
    "NewProjectRequest",
    "ProgressEvent",
    "ProjectAvailability",
    "ProjectCatalogEntry",
    "ProjectDeletionAvailability",
    "ProjectDeletionInspection",
    "ProjectDeletionResult",
    "ProjectDestinationInspection",
    "ProjectSummary",
    "ReportDocument",
    "ResourceTelemetryView",
    "SettingResolution",
    "SettingsChangePreview",
    "SettingsScopeKind",
    "SettingsWarning",
    "SourceLocation",
    "SourceInspection",
    "VerificationSettings",
    "VerificationJob",
    "VerificationJobObservation",
    "VerificationJobState",
    "CancellationFlag",
    "ProofAssistantWorkflow",
    "ProjectDeletionError",
    "VerificationJobConflictError",
    "VerificationJobNotCancellableError",
    "VerificationJobNotFoundError",
    "ProjectDestinationError",
    "ReportUnavailableError",
    "StaleChangePlanError",
    "WorkflowSnapshot",
    "WorkflowState",
]


def __getattr__(name: str):
    if name in {
        "CancellationFlag",
        "ProofAssistantWorkflow",
        "ProjectDeletionError",
        "VerificationJobConflictError",
        "VerificationJobNotCancellableError",
        "VerificationJobNotFoundError",
        "ProjectDestinationError",
        "ReportUnavailableError",
        "StaleChangePlanError",
    }:
        from . import service

        return getattr(service, name)
    raise AttributeError(name)
